//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKR.Test.ToscaReportGenerator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ToscaReportGenerator : global::System.Configuration.ApplicationSettingsBase {
        
        private static ToscaReportGenerator defaultInstance = ((ToscaReportGenerator)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ToscaReportGenerator())));
        
        public static ToscaReportGenerator Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\TOSCA_PROJECTS\\TOSCA_Workspaces\\BKR Tom\\BKR Tom.tws")]
        public string workspacePath {
            get {
                return ((string)(this["workspacePath"]));
            }
            set {
                this["workspacePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tomw")]
        public string loginName {
            get {
                return ((string)(this["loginName"]));
            }
            set {
                this["loginName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("welkom!01")]
        public string loginPassword {
            get {
                return ((string)(this["loginPassword"]));
            }
            set {
                this["loginPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EVA Batchtoetsen")]
        public string mainExList {
            get {
                return ((string)(this["mainExList"]));
            }
            set {
                this["mainExList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EVABatchtoetsen.xml")]
        public string filenameXml {
            get {
                return ((string)(this["filenameXml"]));
            }
            set {
                this["filenameXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Report.xslt")]
        public string filenameXslt {
            get {
                return ((string)(this["filenameXslt"]));
            }
            set {
                this["filenameXslt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Tom\\XSLT")]
        public string foldername {
            get {
                return ((string)(this["foldername"]));
            }
            set {
                this["foldername"] = value;
            }
        }
    }
}
